
name: Reusable Workflow user

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello

  docker:
    uses: Sridevi-bootlabs/first_workflow/.github/workflows/workflow1.yml@main
    with:
      image_name: azuret4
      tag: v1
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
      
